# Generated by Django 4.1.5 on 2023-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_app_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_shop',
            name='id',
        ),
        migrations.AlterField(
            model_name='app_shop',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
