# Generated by Django 4.1.5 on 2023-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
