# Generated by Django 4.1.5 on 2023-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_alter_user_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebookresponce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
    ]
