# Generated by Django 4.1.5 on 2023-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_facebookresponce'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookresponce',
            name='typee',
            field=models.CharField(default='nott', max_length=100),
        ),
    ]
